# Generated by Django 5.0.4 on 2024-04-23 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_cart_isauthenticated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='product',
            new_name='products',
        ),
    ]
