# Generated by Django 5.0.4 on 2024-04-23 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_product_description'),
        ('user', '0013_cartlines'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CartLines',
            new_name='CartLine',
        ),
    ]
