# Generated by Django 5.0.4 on 2024-04-23 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_rename_cartlines_cartline'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartLine',
        ),
    ]
