# Generated by Django 5.0.4 on 2024-04-23 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_cartline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='isAuthenticated',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='products',
        ),
    ]
