# Generated by Django 5.0.4 on 2024-04-23 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_remove_cart_isauthenticated_remove_cart_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartline',
            old_name='Cart',
            new_name='cart',
        ),
        migrations.RenameField(
            model_name='cartline',
            old_name='Product',
            new_name='product',
        ),
    ]
